employees/.idea/dataSources.xml, employees/.idea/inspectionProfiles/Project_Default.xml, employees/.idea/jpa-buddy.xml, employees/src/main/java/raf/bolnica1/employees/controllers/EmployeeController.java, employees/src/main/java/raf/bolnica1/employees/dto/employee/EmployeeCreateDto.java, employees/src/main/java/raf/bolnica1/employees/dto/employee/EmployeeDto.java, employees/src/main/java/raf/bolnica1/employees/dto/employee/EmployeeMessageDto.java, employees/src/main/java/raf/bolnica1/employees/dto/employee/EmployeeUpdateAdminDto.java, employees/src/main/java/raf/bolnica1/employees/dto/employee/EmployeeUpdateDto.java, employees/src/main/java/raf/bolnica1/employees/exceptions/department/DepartmentNotFoundException.java, employees/src/main/java/raf/bolnica1/employees/exceptions/employee/EmployeeAlreadyExistsException.java, employees/src/main/java/raf/bolnica1/employees/exceptions/employee/EmployeeNotFoundException.java, employees/src/main/java/raf/bolnica1/employees/exceptions/employee/EmployeePasswordException.java, employees/src/main/java/raf/bolnica1/employees/mappers/EmployeeMapper.java, employees/src/main/java/raf/bolnica1/employees/repository/EmployeeRepository.java, employees/src/main/java/raf/bolnica1/employees/runner/TestDataRunner.java, employees/src/main/java/raf/bolnica1/employees/security/SpringSecurityConfig.java, employees/src/main/java/raf/bolnica1/employees/services/EmployeeService.java, employees/src/main/java/raf/bolnica1/employees/services/impl/EmployeeServiceImpl.java, employees/src/main/resources/application.properties
Implementirane CRUD operacije za employee, dodate DTO klase, sredjeni kontroleri i napravljene izmene u spring security da bi H2 mogla da se otvori u localhost. Takodjene uradjeno filtriranje zaposlenih (paginacija).
=> Implementirane CRUD operacije i paginacija

employees/pom.xml, employees/src/main/java/raf/bolnica1/employees/checking/jwtService/TokenService.java, employees/src/main/java/raf/bolnica1/employees/checking/jwtService/TokenServiceImpl.java, employees/src/main/java/raf/bolnica1/employees/communication/request/LoginRequest.java, employees/src/main/java/raf/bolnica1/employees/controllers/AuthController.java, employees/src/main/java/raf/bolnica1/employees/repository/EmployeeRepository.java, employees/src/main/java/raf/bolnica1/employees/repository/EmployeesPrivilegeRepository.java, employees/src/main/java/raf/bolnica1/employees/runner/TestDataRunner.java, employees/src/main/java/raf/bolnica1/employees/security/SpringSecurityConfig.java, employees/src/main/java/raf/bolnica1/employees/services/AuthService.java, employees/src/main/resources/application.properties
Implementirao sam generisanje JWT tokena na osnovu zahteva korisnika prilikom Log in faze
Ispravio sam typo u application.properties
Fixovao sam bug u TestRunner klasi, jer su mogla da postoje vise korisnika sa istim username
=> Implementirana autentifikacija zaposlenih

employees/src/main/java/raf/bolnica1/employees/domain/Employee.java, employees/src/main/java/raf/bolnica1/employees/dto/employee/EmployeeCreateDto.java, employees/src/main/java/raf/bolnica1/employees/repository/DepartmentRepository.java, employees/src/main/java/raf/bolnica1/employees/repository/HospitalRepository.java, employees/src/main/java/raf/bolnica1/employees/security/SpringSecurityConfig.java, employees/src/test/java/raf/bolnica1/employees/domainTest/DepartmentTest.java, employees/src/test/java/raf/bolnica1/employees/domainTest/EmployeeTest.java, employees/src/test/java/raf/bolnica1/employees/domainTest/HospitalTest.java
=> Dodati testovi za CRUD (Hospital, Department, Employee) 

patients/src/main/java/raf/bolnica1/patient/controllers/PatientController.java, patients/src/main/java/raf/bolnica1/patient/dto/PatientDtoDesease.java, patients/src/main/java/raf/bolnica1/patient/dto/PatientDtoReport.java, patients/src/main/java/raf/bolnica1/patient/repository/ExaminationHistoryRepository.java, patients/src/main/java/raf/bolnica1/patient/repository/MedicalHistoryRepository.java, patients/src/main/java/raf/bolnica1/patient/repository/MedicalRecordRepository.java, patients/src/main/java/raf/bolnica1/patient/security/SpringSecurityConfig.java, patients/src/main/java/raf/bolnica1/patient/services/PatientService.java
Implementirana logika za dohvatanje pacijenta preko lbp-a, logika za dohvatanje svih izvestaja pregleda preko lbp-a pacijenta i konkretnog datuma ili raspona datuma (od-do) i logika za dohvatanje istorija bolesti preko lbp-a pacijenta i mkb10 (dijagnoza)
=> Implementirane findPatientLBP,hisotryOfDeseasePatient i findReportPatient

examinations/HELP.md, examinations/mvnw, examinations/mvnw.cmd, examinations/pom.xml, examinations/src/main/java/raf/bolnica1/examination/ExaminationApplication.java, examinations/src/main/java/raf/bolnica1/examination/controllers/ExaminationController.java, examinations/src/main/java/raf/bolnica1/examination/security/SpringSecurityConfig.java, examinations/src/main/java/raf/bolnica1/examination/services/ExaminationService.java, examinations/src/main/resources/application.properties, examinations/src/test/java/raf/bolnica1/examination/ExaminationApplicationTests.java
- Dodat pom sa dependenci-ima
- Dodat spring security
- Dodat spring
=> Dodat kostur za ExaminationApplication :

employees/src/main/java/raf/bolnica1/employees/controllers/AuthController.java, employees/src/main/java/raf/bolnica1/employees/services/impl/EmployeeServiceImpl.java, employees/src/test/java/raf/bolnica1/employees/serviceTest/EmployeeServiceTest.java
EmployeeService testovi odradjeni. Svi prolaze. Popravljen mali bag zbog kog je padao jedan test u editEmployeeInfoByAdmin metodi. U AuthControlleru sklonjen import za parser, ne moze da resolve-uje
=> EmployeeService testovi, male popravke u Employee servisu.

employees/pom.xml, employees/src/main/java/raf/bolnica1/employees/config/SwaggerConfig.java, employees/src/main/java/raf/bolnica1/employees/security/SpringSecurityConfig.java, employees/src/main/resources/application.properties, patients/pom.xml, patients/src/main/java/raf/bolnica1/patient/config/SwaggerConfig.java, patients/src/main/java/raf/bolnica1/patient/security/SpringSecurityConfig.java, patients/src/main/resources/application.properties
Nacin na koji je asistent uradio ne radi za nas zbog java verzije, zahteva 2 dependecija umesto jednog, sve ostalo je isto. Za emloyees servis radi, dok u patients ne, pretpostavljam da ima neke veze sa SecurityConfiguration i filterima.
=> Swagger dodat u oba servisa, employee radi, patients ne

infirmary/pom.xml, infirmary/src/main/java/raf/bolnica1/infirmary/domain/DischargeList.java, infirmary/src/main/java/raf/bolnica1/infirmary/domain/HospitalRoom.java, infirmary/src/main/java/raf/bolnica1/infirmary/domain/Hospitalization.java, infirmary/src/main/java/raf/bolnica1/infirmary/domain/PatientState.java, infirmary/src/main/java/raf/bolnica1/infirmary/domain/Prescription.java, infirmary/src/main/java/raf/bolnica1/infirmary/domain/ScheduledAppointment.java, infirmary/src/main/java/raf/bolnica1/infirmary/domain/Visit.java, infirmary/src/main/java/raf/bolnica1/infirmary/domain/constants/AdmissionStatus.java, infirmary/src/main/java/raf/bolnica1/infirmary/domain/constants/PrescriptionStatus.java, infirmary/src/main/java/raf/bolnica1/infirmary/domain/constants/PrescriptionType.java, infirmary/src/main/java/raf/bolnica1/infirmary/repository/DischargeListRepository.java, infirmary/src/main/java/raf/bolnica1/infirmary/repository/HospitalRoomRepository.java, infirmary/src/main/java/raf/bolnica1/infirmary/repository/HospitalizationRepository.java, infirmary/src/main/java/raf/bolnica1/infirmary/repository/PatientStateRepository.java, infirmary/src/main/java/raf/bolnica1/infirmary/repository/PrescriptionRepository.java, infirmary/src/main/java/raf/bolnica1/infirmary/repository/ScheduledAppointmentRepository.java, infirmary/src/main/java/raf/bolnica1/infirmary/repository/VisitRepository.java, infirmary/src/main/resources/application.properties
Dodati modeli za stacionar i repository. Napravljene izmene u application.properties. Zakomentarisan security dok se ne doda, da bi konzola za bazu mogla da se otvori.
=> Modeli za stacionar

infirmary/src/main/java/raf/bolnica1/infirmary/controllers/InfirmaryController.java, infirmary/src/main/java/raf/bolnica1/infirmary/domain/DischargeList.java, infirmary/src/main/java/raf/bolnica1/infirmary/domain/Hospitalization.java, infirmary/src/main/java/raf/bolnica1/infirmary/repository/HospitalRoomRepository.java, infirmary/src/main/java/raf/bolnica1/infirmary/repository/HospitalizationRepository.java, infirmary/src/main/java/raf/bolnica1/infirmary/repository/PrescriptionRepository.java, infirmary/src/main/java/raf/bolnica1/infirmary/services/InfirmaryService.java
Dodati paketi services,controllers i dto i dodate gore navedene metode.
=> Napravljene metode za kreiranje otpusne liste,pretragu bolnickih soba i hospitalizaciju pacijenta

infirmary/src/main/java/raf/bolnica1/infirmary/controllers/InfirmaryController.java, infirmary/src/main/java/raf/bolnica1/infirmary/domain/HospitalRoom.java, infirmary/src/main/java/raf/bolnica1/infirmary/domain/PatientState.java, infirmary/src/main/java/raf/bolnica1/infirmary/domain/Prescription.java, infirmary/src/main/java/raf/bolnica1/infirmary/domain/ScheduledAppointment.java, infirmary/src/main/java/raf/bolnica1/infirmary/domain/Visit.java, infirmary/src/main/java/raf/bolnica1/infirmary/runner/TestDataRunner.java, infirmary/src/main/java/raf/bolnica1/infirmary/services/InfirmaryService.java
Dodata klasa TestDataRunner sa implementacijom za popunjavanje baze radi lakseg testiranja metoda, napravljene male izmene na metodi koja dohvata bolnicke sobe
=> Dodata klasa TestDataRunner i napravljene male izmene na metodi koja dohvata bolnicke sobe

laboratory/src/main/java/raf/bolnica1/laboratory/controllers/LaboratoryExaminationsController.java, laboratory/src/main/java/raf/bolnica1/laboratory/domain/lab/ScheduledLabExamination.java, laboratory/src/main/java/raf/bolnica1/laboratory/exceptions/ExceptionHandlerController.java, laboratory/src/main/java/raf/bolnica1/laboratory/exceptions/examinations/ExaminationNotFoundException.java, laboratory/src/main/java/raf/bolnica1/laboratory/services/lab/LabExaminationsService.java, laboratory/src/main/java/raf/bolnica1/laboratory/services/lab/impl/LabExaminationsServiceImpl.java, laboratory/src/main/resources/application.properties, laboratory/src/test/java/raf/bolnica1/laboratory/serviceTest/LabExaminationServiceTest.java
Dodata funkcionalnost za izmenu pregleda(Ukljucujuci i unit test), kao i izbacivanje Bearer koji se ponavljao, i modifikacija linka za h2 bazu. Takodje dodat exception ako se menja nepostojeci pregled.
=> Menjanje pregleda sa testom i promene manje

infirmary/src/main/java/raf/bolnica1/infirmary/controllers/AppointmentController.java, infirmary/src/main/java/raf/bolnica1/infirmary/repository/ScheduledAppointmentRepository.java, infirmary/src/main/java/raf/bolnica1/infirmary/services/AppointmentService.java, infirmary/src/main/java/raf/bolnica1/infirmary/services/impl/AppointmentServiceImpl.java
- implements https://github.com/RAF-SI-2022/Bolnica-1-Backend/issues/110
TODO : Prilikom promene Statusa pregleda mora se ažurirati i Status o prispeću pacijenta
=> Implement Azuriranje statusa pregleda :

patients/src/test/java/raf/bolnica1/patient/services/cucumber/medicalexaminationservice/MedicalExaminationServiceTests.java, patients/src/test/java/raf/bolnica1/patient/services/cucumber/medicalexaminationservice/MedicalExaminationServiceTestsConfig.java, patients/src/test/java/raf/bolnica1/patient/services/cucumber/medicalexaminationservice/MedicalExaminationServiceTestsSteps.java, patients/src/test/resources/features/medicalexaminationservice/medical-examination-service-tests.feature
Testirao MedicalExaminationService(Nije jos gotovo)
=> Testiranje MedicalExaminationService

patients/src/main/java/raf/bolnica1/patient/dto/general/AllergyDto.java, patients/src/test/java/raf/bolnica1/patient/services/impl/MedicalRecordServiceImplTest.java
Odradjeni svi testovi za MedicalRecordServiceImpl
Dodate anotacije za konstruktor na AllergyDto zarad lakseg testiranja.
=> Unit testing MedicalRecordServiceImpl

patients/src/test/java/raf/bolnica1/patient/services/impl/MedicalExaminationServiceImplTest.java
Uradjeni unit testovi za MedicalExaminationServiceImpl
=> Unit testing MedicalExaminationServiceImpl

patients/src/test/java/raf/bolnica1/patient/cucumber/findinfoservice/FindInfoServiceTests.java, patients/src/test/java/raf/bolnica1/patient/cucumber/findinfoservice/FindInfoServiceTestsConfig.java, patients/src/test/java/raf/bolnica1/patient/cucumber/findinfoservice/FindInfoServiceTestsSteps.java, patients/src/test/java/raf/bolnica1/patient/cucumber/medicalexaminationservice/MedicalExaminationServiceTests.java, patients/src/test/java/raf/bolnica1/patient/cucumber/medicalexaminationservice/MedicalExaminationServiceTestsConfig.java, patients/src/test/java/raf/bolnica1/patient/cucumber/medicalexaminationservice/MedicalExaminationServiceTestsSteps.java, patients/src/test/java/raf/bolnica1/patient/cucumber/medicalrecordservice/MedicalRecordServiceTests.java, patients/src/test/java/raf/bolnica1/patient/cucumber/medicalrecordservice/MedicalRecordServiceTestsConfig.java, patients/src/test/java/raf/bolnica1/patient/cucumber/medicalrecordservice/MedicalRecordServiceTestsSteps.java, patients/src/test/java/raf/bolnica1/patient/cucumber/patientcrudservice/PatientCrudServiceTests.java, patients/src/test/java/raf/bolnica1/patient/cucumber/patientcrudservice/PatientCrudServiceTestsConfig.java, patients/src/test/java/raf/bolnica1/patient/cucumber/patientcrudservice/PatientCrudServiceTestsSteps.java, patients/src/test/java/raf/bolnica1/patient/cucumber/patientservice/PatientServiceTests.java, patients/src/test/java/raf/bolnica1/patient/cucumber/patientservice/PatientServiceTestsConfig.java, patients/src/test/java/raf/bolnica1/patient/cucumber/patientservice/PatientServiceTestsSteps.java, patients/src/test/resources/features/findinfoservice/find-info-service-tests.feature, patients/src/test/resources/features/medicalrecordservice/medical-record-service-tests.feature
Premesteni paketi kako bi projekat i integracioni testovi mogli da se pokrenu
=> Napravljene promene na integracionim testovima

patients/src/main/java/raf/bolnica1/patient/runner/TestDataRunner.java, patients/src/test/java/raf/bolnica1/patient/cucumber/medicalrecordservice/MedicalRecordServiceTestsSteps.java, patients/src/test/resources/features/medicalrecordservice/medical-record-service-tests.feature
Napravljene male promene vezane za testove za MedicalRecordServiceIml i takodje dodato malo parce koda u TestDataRunneru da bi se moglo pokrenuti nekoliko testova
=> Napravljene male promene vezane za testove MedicalRecordServiceImpl i TestDataRunner

patients/src/test/java/raf/bolnica1/patient/services/impl/FindInfoServiceImplTest.java, patients/src/test/java/raf/bolnica1/patient/services/impl/PatientServiceImplTest.java
20/21 testova radi treba samo jos jedan taj da popravim, bice vrv u toku dana.
=> Unit testing FindINfoService

patients/src/test/java/raf/bolnica1/patient/services/impl/FindInfoServiceImplTest.java
Jedan unit test koji nije radio u FindInfoService sada radi.
=> Popravljen unit test u FindInfoService

patients/src/test/java/raf/bolnica1/patient/services/impl/PatientServiceImplTest.java
Dodao sam jos 5-6 testova koji su falili i zamnio one koji nisu, zakomentarisani su za svaki slucaj ako je osoba koja je pisala htela da koriguje. Jedan test ne radi samo to cu sutra poslati.
=> Doradjeni unit testovi u PatientService

patients/src/test/java/raf/bolnica1/patient/services/impl/PatientServiceImplTest.java
Popravljen unit test koji nije radio.
=> Popravljen unit test u PatientService

employees/src/test/java/raf/bolnica1/employees/dataGenerators/HospitalDepartmentGenerator.java, employees/src/test/java/raf/bolnica1/employees/dataGenerators/primitives/RandomDate.java, employees/src/test/java/raf/bolnica1/employees/dataGenerators/primitives/RandomDouble.java, employees/src/test/java/raf/bolnica1/employees/dataGenerators/primitives/RandomLong.java, employees/src/test/java/raf/bolnica1/employees/dataGenerators/primitives/RandomNames.java, employees/src/test/java/raf/bolnica1/employees/dataGenerators/primitives/RandomString.java, employees/src/test/java/raf/bolnica1/employees/dataGenerators/primitives/RandomTime.java, employees/src/test/java/raf/bolnica1/employees/dataGenerators/primitives/RandomTimestamp.java, employees/src/test/java/raf/bolnica1/employees/serviceTest/DepartmentServiceTest.java, employees/src/test/java/raf/bolnica1/employees/validation/ClassJsonComparator.java
Push da bi i viktor mogao da se nadoveze na generatore i validacije koje se koriste u testovima.
=> Employee tests
